name: mantenimiento_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Hacer la restricción del SDK más flexible

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0 # Para formato de fechas (actualizado a 0.20.2 en el último pub get)
  http: ^1.2.1  # Para hacer peticiones HTTP (simuladas por ahora)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Asegurarse de que esta línea esté solo una vez

# Configuración específica de Flutter
flutter:
  uses-material-design: true

  # Declaración de assets (archivos de datos, imágenes, etc.)
  assets:
    - assets/descripcion.txt # Tu archivo de ubicación técnica
    # Puedes descomentar la siguiente línea si planeas añadir más archivos en la carpeta assets/
    # - assets/

  # Sección para fuentes personalizadas (ejemplo comentado)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

# Configuración para deploy_kit (al mismo nivel que 'name', 'description', etc.)
deploy_kit:
  github_pages:
    branch: gh-pages # La rama que usará para el despliegue
    build_dir: build/web # El directorio donde se construye la app web